### ISSUE TITLE
Unban reconnect

### ISSUE THREAD

**Issue by i3aq** [Ch40zz/CCHookReloaded#7]
when pressing f10 not sure what "screen" or "when" you are supposed to press it like straight after getting banned while having the ban image on the main menu or whatever, anyways upon pressing f10 the game just crashes, didn't have this problem a few days ago but seems to just crash now and does nothing else? not sure what it could be (also ETL 2.82.0 releases in 1 day or 2 if you aren't aware) (i tested this on all mods: nitmod, silentmod i got banned by anti cheat and still didnt work, jaymod, legacy, no quarter)

**Comment by i3aq** [comment]
![image_2024-03-07_083810053](https://github.com/Ch40zz/CCHookReloaded/assets/119784933/7176cbe6-9a22-4d78-926a-6b7c546b300e)
also this happens when you connect to some nitmod/jaymod/silent servers, doesn't happen to all of them which is weird

this prevents you from joining to a team, if you join to any team you will get kicked for sv_usercommand overflow or whatever

**Comment by greatmole** [comment]
![2024-03-06 14_55_08-ET Legacy](https://github.com/Ch40zz/CCHookReloaded/assets/112938140/382df925-8c31-4915-aab3-684686275732)
Welcom ! same for me...

**Comment by greatmole** [comment]
and more !!! as admin of my server, impossible to enter the rcon or referee code... so I can not enter any command...

**Comment by i3aq** [comment]
> and more !!! as admin of my server, impossible to enter the rcon or referee code... so I can not enter any command...

you could try 2 different clients on your "server" so say your main client "either 2.60b or ET legacy" you can have your admin run on 2.60b and type commands etc then run your cheat on ETL and join, this way you should be able to test it

**Comment by Ch40zz** [comment]
Does the command delay happen on 2.60b too or only on legacy?
Did you notice anything you needed to do (e.g. enable a certain feature) to cause the command delay?
Do you have an IP for a server which doesn't have annoying hardware bans where we can test/reproduce this problem?

For the quick reconnect does it work on 2.60b and only crashes on legacy or crashes on both?
EDIT: Game crashes on vid_restart apparently

**Comment by Ch40zz** [comment]
I pushed a fix for the quick reconnect, They apparently fucked up their code. Dynamic shader loading crashes the ETL  client on vid_restart, didn't investigate their bug yet tho lol

**Comment by i3aq** [comment]
> Does the command delay happen on 2.60b too or only on legacy? Did you notice anything you needed to do (e.g. enable a certain feature) to cause the command delay? Do you have an IP for a server which doesn't have annoying hardware bans where we can test/reproduce this problem?
> 
> For the quick reconnect does it work on 2.60b and only crashes on legacy or crashes on both? EDIT: Game crashes on vid_restart apparently

yeah i know quite a few servers that we can use i dont own them but they are always empty, and yes it also crashes with vid_restart forgot to add that also and it also doesnt matter what settings you have this will still happen regardless

**Comment by i3aq** [comment]
> Does the command delay happen on 2.60b too or only on legacy? Did you notice anything you needed to do (e.g. enable a certain feature) to cause the command delay? Do you have an IP for a server which doesn't have annoying hardware bans where we can test/reproduce this problem?
> 
> For the quick reconnect does it work on 2.60b and only crashes on legacy or crashes on both? EDIT: Game crashes on vid_restart apparently

and that sv_userinfooverflow shit only happens on nitmod/silent/noquarter/jaymod but never on legacy servers

**Comment by i3aq** [comment]
![image](https://github.com/Ch40zz/CCHookReloaded/assets/119784933/3ef7548c-9711-4162-a138-9b6f64a82100)
![image](https://github.com/Ch40zz/CCHookReloaded/assets/119784933/e36f8c9e-4a8f-4c45-87f2-b7da120e8a8d)

the FA servers seems to have an updated version of the "legacy" server version both utilising the same mod version so it cant be that. the team bunny server is connectable and no problems will come your way (no anti cheat or any of that sv_userinfoflood protection)

as for the FA servers they found some way to keep cheaters banned, dont know if i did it right or wrong but cant reconnect to any FA server with spoofed hwid or ip or guid, same goes with hirntot (i believe hirntot use some sort of lua script), 

(this following attempt was tried on polskie swiry xp save( a nitmod server))
![image](https://github.com/Ch40zz/CCHookReloaded/assets/119784933/d1ae036d-bf68-43d9-a24a-7b593b60f245)
this is the error upon getting kicked for the "sv_userinfofloodprotect"

you dont have any time to disable any cheat features but i guess i could try turning them off in the config instead
(i turned them all off in the config file and still cant do anything, with no features enabled the game is running for about 2-3 seconds before it crashes where i got this error again 

![image](https://github.com/Ch40zz/CCHookReloaded/assets/119784933/3f969665-676f-43f6-a9f6-61b2cea3f0b9)

tried to reconnect after being kicked and this happened 
![image](https://github.com/Ch40zz/CCHookReloaded/assets/119784933/c2e57d20-9851-46b3-9468-b2ba6e8c0bf8)

**Comment by i3aq** [comment]
it seems now upon joining any nitmod server (this was done both with/without settings enabled in the cheat) i just seem to get disconnected and recieve this error
![image](https://github.com/Ch40zz/CCHookReloaded/assets/119784933/898861ec-95d2-4d48-8e6d-f9932d7c2cfb)

if i try to reconnect my game just crashes, even when i try to join another nitmod server that has this issue (as i said before some servers dont have this issue on them which is weird seems to only be the ones with anti cheat enabled (mainly nxac))

**Comment by greatmole** [comment]
I have the same message on my server with every map change. But I reconnect and everything is fine... until the next map

**Comment by greatmole** [comment]
I have the same message on my server with every map change. But I reconnect and everything is fine... until the next map

**Comment by Ch40zz** [comment]
I updated the cheat for 2.82.0 and connected to 194.110.5.166:27960 (polskie swiry xp save), no issues or disconnects.
Maybe you can re-test and see if its working now. Also the quick reconnect has been fixed too :)

**Comment by i3aq** [comment]
> I updated the cheat for 2.82.0 and connected to 194.110.5.166:27960 (polskie swiry xp save), no issues or disconnects. Maybe you can re-test and see if its working now. Also the quick reconnect has been fixed too :)


))) Did you test this with the original version or the steam version? for some reason wont let me direct the exe to the game exe just says failed to create process 

EDIT: turns out you cannot launch ET Legacy as a administrator and inject the dll into the game, if you are trying to direct the "cchook.exe" into the etl.exe make sure you go to the properties for etl.exe and make sure to turn off the "run as administrator" option --- fix for this is to run the cchook.exe as admin too then you can run steam/legacy as admin also

another edit: after playing on polski swiry xp save for about 5 minutes it was fine until it started to get really laggy and disconnected me several times, as for most legacy servers have disabled vpn's on their servers



![image](https://github.com/Ch40zz/CCHookReloaded/assets/119784933/d2c2cb0a-f9b2-433a-966b-9f46b53b110a)
this seems to happen on some nitmod, jaymod and silent servers still

with or without settings enabled in the cheat pretty weird

an easy fix to this is just to use the steam version, seems the steam version has no problems connecting to any server than ET legacy

**Comment by greatmole** [comment]
A vpn, a mac address changed, and yet banned... they spotted me quickly I think

**Comment by Ch40zz** [comment]
> > I updated the cheat for 2.82.0 and connected to 194.110.5.166:27960 (polskie swiry xp save), no issues or disconnects. Maybe you can re-test and see if its working now. Also the quick reconnect has been fixed too :)
> 
> ))) Did you test this with the original version or the steam version? for some reason wont let me direct the exe to the game exe just says failed to create process
> 
> EDIT: turns out you cannot launch ET Legacy as a administrator and inject the dll into the game, if you are trying to direct the "cchook.exe" into the etl.exe make sure you go to the properties for etl.exe and make sure to turn off the "run as administrator" option --- fix for this is to run the cchook.exe as admin too then you can run steam/legacy as admin also
> 
> another edit: after playing on polski swiry xp save for about 5 minutes it was fine until it started to get really laggy and disconnected me several times, as for most legacy servers have disabled vpn's on their servers
> 
> ![image](https://private-user-images.githubusercontent.com/119784933/312058720-d2c2cb0a-f9b2-433a-966b-9f46b53b110a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzNjA5OTgsIm5iZiI6MTcxMDM2MDY5OCwicGF0aCI6Ii8xMTk3ODQ5MzMvMzEyMDU4NzIwLWQyYzJjYjBhLWY5YjItNDMzYS05NjZiLTlmNDZiNTNiMTEwYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxM1QyMDExMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MGI1ZGFmMGZlYzQ3ZWQ4OTVlNDM5ZjQyYjE5NDUxY2UzMWU1YWU3ODk5ZmY0MTUyMGMyMTNhMjQ1NDc4OTRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tJW2ZgLFE8xAHfLPsmvJWSi_K_J9N2bU5KMzb6uByQ4) this seems to happen on some nitmod, jaymod and silent servers still
> 
> with or without settings enabled in the cheat pretty weird
> 
> an easy fix to this is just to use the steam version, seems the steam version has no problems connecting to any server than ET legacy

I tested everything with ET Legacy client, not steam (which is 2.60b).
To launch the microsoft app you need to run the injector as admin, they do stupid shit with the folder access rights.
I played for an hour on the server and had no issues, its hard for me to try figuring out the issue if Im not affected xD

**Comment by i3aq** [comment]
> I tested everything with ET Legacy client, not steam (which is 2.60b). To launch the microsoft app you need to run the injector as admin, they do stupid shit with the folder access rights. I played for an hour on the server and had no issues, its hard for me to try figuring out the issue if Im not affected xD

not really sure what it could be then, i mean it only happens for me on some servers so maybe try to join to some more servers? just afk for a few minutes or whatever and move to the next.

**Comment by i3aq** [comment]
also just another thing but what exactly does the f10 unban reconnect do?

**Comment by Ch40zz** [comment]
> also just another thing but what exactly does the f10 unban reconnect do?

It does the following:
- create a new random etkey
- backup old etkey
- randomize etpro guid
- execute the following command: `pb_myguid; net_port 27???; net_restart; vid_restart; pb_myguid; reconnect`

**Comment by i3aq** [comment]
> > also just another thing but what exactly does the f10 unban reconnect do?
> 
> It does the following:
> 
> * create a new random etkey
> * backup old etkey
> * randomize etpro guid
> * execute the following command: `pb_myguid; net_port 27???; net_restart; vid_restart; pb_myguid; reconnect`

making anything related to etpro in the cheat now is pretty much useless since punkbuster is no longer a thing in et, although its still possible to play etpro so i guess keep it in

also you can close this now if you want if anything else i notice ill let you know :)
